chatgpt:
  token: "![wYUYx00UeNiW1VYMAjQXFXfctilGhrO4J272yAoTpPqs/SMF7OY+LBEHk+C+Xt7+OSP8kVEAca8o3RWtmT5zgA==]"
  
database:
  url: "jdbc:postgresql://localhost:5432/orders"
  user: "postgres"
  password: "![xWhsDdo45Fa20ErMWPjR+A==]"