#%RAML 1.0 Trait
headers:
  client_id:
    description: Client ID used for authorization.
    type: string
    required: true
    example: u10eu1auu1c2u51u13731u655e6c16u6
  client_secret:
    description: Client secret used for authorization.
    type: string
    required: true
    example: 11eh7357B46d4CdDBfh5ce7cE1b401hA 